builddeb: use l4t-submodules files for JP/L4T version
In the preinst script that builddeb creates, get the desired JetPack and
L4T versions from the files in l4t-submodules.

Change-Id: Ic1939f62d2a435c68f4ae5df67d8339d9df1ed6a

diff --git a/scripts/package/builddeb b/scripts/package/builddeb
--- a/scripts/package/builddeb
+++ b/scripts/package/builddeb
@@ -201,26 +201,37 @@ if grep -q '^CONFIG_BLK_DEV_INITRD=y' $KCONFIG_CONFIG; then
 else
 	want_initrd=No
 fi
+
+# Get the version numbers we want to check in the preinst script
+olddir=`pwd`
+here=`dirname "$0"`
+cd "$here"
+here=`pwd`
+cd "$olddir"
+jetpack_target=`cat "$here/../../jp_version.txt" || true`
+l4t_target=`cat "$here/../../l4t_version.txt" || true`
+
 for script in postinst postrm preinst prerm ; do
 	mkdir -p "$tmpdir$debhookdir/$script.d"
 	echo "#!/bin/bash" > "$tmpdir/DEBIAN/$script"
-	if [[ "$script" = preinst ]]; then
+
+	if [ "$script" = 'preinst' ] && [ "$jetpack_target" ] && [ "$l4t_target" ] ; then
 		cat <<EOF >> "$tmpdir/DEBIAN/$script"
 
 # Check L4T version for compatibility
 # Intended version
-JETPACK_VER="4.2.2"
-L4T_EXPECTED="32.2.1"
+JETPACK_VER="$jetpack_target"
+L4T_EXPECTED="$l4t_target"
 
 # Get the L4T version currently installed
-L4T_VER="\$(perl -ne 'exit 1 unless /R([\d\.]+).*?REVISION: ([\d\.]+)/; print "\$1.\$2\n"; exit 0' /etc/nv_tegra_release)"
+L4T_VER="\$(perl -ne 'exit 1 unless /R([\\d\\.]+).*?REVISION: ([\\d\\.]+)/; print "\$1.\$2\n"; exit 0' /etc/nv_tegra_release)"
 GOT_VER_OK="\$?"
 
 if [[ "\$L4T_VER" != "\$L4T_EXPECTED" || "\$GOT_VER_OK" -ne 0 ]]; then
     if [[ -n "\$L4T_VER" && "\$GOT_VER_OK" -eq 0 ]]; then
-        printf "\e[33mWARNING:\e[0m This release is meant for Linux for Tegra v"\$L4T_EXPECTED" (JetPack "\$JETPACK_VER").\nCompatibility with the installed version (v"\$L4T_VER") cannot be guaranteed, and may cause problems.\nInstall anyway? (y/n):"
+        printf "\\e[33mWARNING:\\e[0m This release is meant for Linux for Tegra v"\$L4T_EXPECTED" (JetPack "\$JETPACK_VER").\\nCompatibility with the installed version (v"\$L4T_VER") cannot be guaranteed, and may cause problems.\\nInstall anyway? (y/n):"
     else
-        printf "\e[33mWARNING:\e[0m Unable to determine installed version of Linux for Tegra.\nIf version "\$L4T_EXPECTED" (JetPack "\$JETPACK_VER") is installed, you may continue.\nOtherwise, compatibility cannot be guaranteed.\nContinue installation? (y/n):"
+        printf "\\e[33mWARNING:\\e[0m Unable to determine installed version of Linux for Tegra.\\nIf version "\$L4T_EXPECTED" (JetPack "\$JETPACK_VER") is installed, you may continue.\\nOtherwise, compatibility cannot be guaranteed.\\nContinue installation? (y/n):"
     fi
 
     while read choice; do
